name: quanttide_connect
description: 量潮沟通工程 Dart SDK
version: 0.1.0
homepage: https://github.com/quanttide/quanttide-connect-toolkit
repository: https://github.com/quanttide/quanttide-connect-toolkit

environment:
  sdk: ^3.11.5

dev_dependencies:
  test: ^1.25.0
